### ISSUE TITLE
Failed to enable unit: Unit file ebusd.service does not exist.

### ISSUE THREAD

**Issue by ChrisLan12** [john30/ebusd-esp32#12]
Hello,
I have installed, compiled and done everything from the "Build and install" manual.
At least, I get the Message "Failed to enable unit: Unit file ebusd.service does not exist." when I try to start the ebusd-service with 
sudo systemctl enable ebusd
and
sudo service ebusd start
Greetings
Christoph

**Comment by john30** [comment]
wrong repo as this is ebusd related and not adapter.
anyway, when compiling manually you need to install the appropriate systemd/systemV files from https://github.com/john30/ebusd/tree/master/contrib/debian
