### ISSUE TITLE
eBus Stecker welcher PIN + und -

### ISSUE THREAD

**Issue by homa57** [john30/ebusd-esp32#16]
Welcher PIN ist + und welcher - bei dem eBus Stecker?
In der Grafik fehlt diese Beschriftung. In der Doku habe ich auch nichts gefunden.
Ich frage lieber vorher :-)

**Comment by HeikoGr** [comment]
https://adapter.ebusd.eu/v5/steps.html#ebusconn :
`Auf die Polung braucht dabei keine Rücksicht genommen zu werden`

**Comment by john30** [comment]
indeed, no need to take care for the direction
