### ISSUE TITLE
Power source via USB

### ISSUE THREAD

**Issue by alexferrari88** [john30/ebusd-esp32#17]
Hello, forgive my super basic and noob question but I need to buy a power adapter to power the device via USB. Which specs should I look for? Volts, ampere, etc...

**Comment by HeikoGr** [comment]
any standard compliant micro-b power supply should work.

**Comment by john30** [comment]
I've just added a section about powering to the docs: https://adapter.ebusd.eu/v5/index.en.html#power

**Comment by alexferrari88** [comment]
Thank you!
