### ISSUE TITLE
Network works only with WIFI/client on

### ISSUE THREAD

**Issue by Dennis1000** [john30/ebusd-esp32#19]
I've connected to the adapter via WIFI "ebus", configured both WIFI client (dynamic IP) AND network (using a USR-ES1) with static IP address, saved and rebooted and it works. But as soon as I disable the WIFI connection and reboot, the adapter is pingable on the fixed network address but the UI doesn't show up.
Enabling both the WIFI client (starting from scratch via "ebus" WIFI again) and enabling the network, the UI shows up on both IPs (network and WIFI).

Build: 20230903 Adapter V5, [ESP32-C3, rev 4]

**Comment by john30** [comment]
good catch! solved in next version

**Comment by john30** [comment]
could you check with the [new firmware 20230917](https://adapter.ebusd.eu/v5/ChangeLog#20230917) just released?

**Comment by Dennis1000** [comment]
Works perfectly. Disabled WIFI/client, did a reboot and the UI shows up! Thanks!

**Comment by john30** [comment]
great, thanks!
