### ISSUE TITLE
Update firmware by webUI

### ISSUE THREAD

**Issue by pepsonEL** [john30/ebusd-esp32#20]
Hi
Is any chance to implement to this version option update FW by WebUI (not by wire) ?

**Comment by john30** [comment]
when I have time to and it fits in the available room with ebusd

**Comment by VivantSenior** [comment]
@john3, were you able to implement OTA from WebUI in ESP32-C3 rev 4? I found information on [this page](https://adapter.ebusd.eu/v5/steps.en.html#adapterflash):
`Newer firmware versions can be easily updated via OTA directly on the adapter website.`
but was unable to find it in the WebUI:
![image](https://github.com/john30/ebusd-esp32/assets/49829548/bd2f1fca-d14f-4cfb-b295-5fc61c614b95)

**Comment by VivantSenior** [comment]
After [manual update](https://adapter.ebusd.eu/v5/firmware.en#flash) to 20231217 I was able to find "Update firmware" button:
![image](https://github.com/john30/ebusd-esp32/assets/49829548/756990f1-771b-4da1-bf08-e532bf50fbba)

**Comment by john30** [comment]
yes
