### ISSUE TITLE
Problem with authorization

### ISSUE THREAD

**Issue by pepsonEL** [john30/ebusd-esp32#22]
Hi
I use your adapter v5 and setup authorization. I use user as: " admin" and password "16 characters (7 letters + 8 digits + special character)". After that i can not login to my adapter. I try many times login and then flash adapter and again setup and the same problem.

**Comment by john30** [comment]
what firmware version and browser do you use?

**Comment by pepsonEL** [comment]
Firmware Version 2023-09-03 and browser Chrome 117.0.5938.92

**Comment by john30** [comment]
that version has a rather low timeout of 5 seconds for entering the credentials. try with the recent one

**Comment by pepsonEL** [comment]
On version 2023-09-17 all is ok. Thanks
