### ISSUE TITLE
GPIO connecting causing ssh terminal lag?

### ISSUE THREAD

**Issue by unikinCK** [john30/ebusd-esp32#23]
Hi, ever since i installed the raspberrypi via the GPIO the ssh terminal seems to lag a bit. I guess it has to do with the GPIO interrupt? Any chance that it would work better over the raspberrypi USB port? Newest firmware, i followed your tutorial which is really good.

**Comment by john30** [comment]
just give it a try. I could indeed imagine that the UART interrupts cause some extra load, but USB would do similar. anyway, the USB driver might do a bit less load wrt interrupts as it is capable of transferring up to 64 bytes at once
