### ISSUE TITLE
No signal when connecting to Saunier Duval Helioset

### ISSUE THREAD

**Issue by danotrilogic** [john30/ebusd-esp32#27]
Hi,

I would like to monitor some parameters of my Helioset but when I connect my ebus adapter v5 to the ebus port I don't get any signal. I read all the documentation of the device and I don't find any mention to ebus activation or something like that.

Has anyone had any experience with this kind of devices?

Thanks in advance.

**Comment by john30** [comment]
don't know that heater. are you sure it is an eBUS indeed?

some devices claim to have an eBUS connector but don't have a SYN generator active. for this case you can make ebusd the SYN generator unit by adding "--generatesyn" to the start parameters.

anyway, everytime the adapter is diconnected from the bus, the green LED will flash shortly as this is a falling edge and as such looks like a received symbol to the device. is that the case? if not, then the eBUS connector probably does not even have a voltage on it (you might check with a multimeter)
