### ISSUE TITLE
Kein Signal zur Weishaupt WTU 15-S

### ISSUE THREAD

**Issue by flipi0815** [john30/ebusd-esp32#30]
Hi!

Das Ebus V5 Shield hängt an einer WTU CPU-B1 von Weishaupt, bekommt aber keinerlei Kommunikation. Anschluss passt 100%. Der ebusd läuft auf einer Debian 12 VM und ist verbunden. 

Kann ich den Adapter durchmessen? Multimeter, Labornetzgerät und Elektrikerkenntnisse vorhanden.

Hier einige Logs und Infos

ebus Adapter info:

`Chip ID: 58cf79e6f978, ESP32-C3, rev 3
Hostname: ebus-weishaupt
PCB: 22.1
Flash: 4194304
Version: v5.2-dev-3318-g8fc8f3f479
Reset reason: 5
eBUS r/w: 1/0
Host r/w: 4/20
Up time: 45
Free heap: 102372
ebusd connected: yes (inactive)
eBUS signal: no signal`

eBus Adapter Log:

 22:50:20 |   | 2 fade started
-- | -- | --
22:50:20 | Info | execute: sleep 1000
22:50:21 | Info | statusLedTimerFn: duty set to 255
22:50:21 | Info | execute: if "isio -l 9" "var skipstart 1"
22:50:21 | Info | execute: isio -l 9
22:50:21 |   | IO 9 level 1 is unmet
22:50:21 | Info | execute: io -iu 6
22:50:21 |   | IO 6 direction set to 01
22:50:21 |   | IO 6 pull set to 00
22:50:21 |   | IO 6 = 1
22:50:21 | Info | execute: var rpi 0
22:50:21 | Info | execute: if "isio -l 6" "var rpi 1"
22:50:21 | Info | execute: isio -l 6
22:50:21 |   | IO 6 level 1 is unmet
22:50:21 | Info | execute: var isnew 1
22:50:21 | Info | execute: if "§isnvs ebus.host" "var isnew 0"
22:50:21 | Info | execute: isnvs ebus.host
22:50:21 | Info | execute: var isnew 0
22:50:21 | Info | execute: if "§isnvs sta.on" "var isnew 0"
22:50:21 | Info | execute: isnvs sta.on
22:50:21 | Info | execute: var isnew 0
22:50:21 | Info | execute: if "§isnvs eth.on" "var isnew 0"
22:50:21 | Info | execute: isnvs eth.on
22:50:21 | Warning | execute: command failed: isnvs eth.on = 1
22:50:21 | Info | execute: on -lo iol 9 "led 0 255" "led 1 255" "led 2 255" "sleep 500" restart
22:50:21 |   | io trigger installed
22:50:21 | Info | execute: on iol 9 "led 2 50 0"
22:50:21 |   | io trigger installed
22:50:21 | Info | execute: if "var skipstart" "led 0 255 0 5000" "led 2 50" "ap EBUS" server exit
22:50:21 | Info | execute: var skipstart
22:50:21 |   | variable skipstart = 0
22:50:21 | Info | execute: function start server "led 0 10"
22:50:21 |   | function installed
22:50:21 | Info | execute: on wifi 1 start
22:50:21 |   | network trigger installed
22:50:21 | Info | execute: on eth 1 start
22:50:21 |   | network trigger installed
22:50:21 | Info | execute: if "isnvs sta.on" "led 0 10 255 5000" "sleep 100" sta
22:50:21 | Info | execute: isnvs sta.on
22:50:21 | Info | execute: led 0 10 255 5000
22:50:21 | Info | execute: sleep 100
22:50:22 | Info | statusLedTimerFn: duty set to 10
22:50:22 | Info | execute: sta
22:50:22 | Info | pp: pp rom version: 9387209
22:50:22 | Info | net80211: net80211 rom version: 9387209
22:50:22 | Info | wifi_init: tcpip mbox: 32
22:50:22 | Info | wifi_init: udp mbox: 6
22:50:22 | Info | wifi_init: tcp mbox: 6
22:50:22 | Info | wifi_init: tcp tx win: 5744
22:50:22 | Info | wifi_init: tcp rx win: 5744
22:50:22 | Info | wifi_init: tcp mss: 1440
22:50:22 | Info | wifi_init: WiFi IRAM OP enabled
22:50:22 | Info | wifi_init: WiFi RX IRAM OP enabled
22:50:22 | Info | wifi_init: LWIP IRAM OP enabled
22:50:22 | Info | phy_init: phy_version 1130,b4e4b80,Sep 5 2023,11:09:30
22:50:22 |   | using individual IP: 192.168.178.119 / 255.255.255.0, gateway 192.168.178.1
22:50:22 |   | sta connecting to 'renz'
22:50:24 | Info | cmd_wifi: sta connect, set fix ip
22:50:24 | Info | repl_event_task: wifi event: 1
22:50:24 | Info | execute: led 0 50
22:50:24 | Info | execute: start
22:50:24 | Info | execute: server
22:50:24 | Info | esp-rest: Starting HTTP Server
22:50:24 |   | server started
22:50:24 | Info | execute: led 0 10
22:50:24 | Info | execute: if "var isnew" "ap EBUS" else "if \"isnvs ap.on\" ap"
22:50:24 | Info | execute: var isnew
22:50:24 |   | variable isnew = 0
22:50:24 | Info | execute: if "isnvs ap.on" ap
22:50:24 | Info | execute: isnvs ap.on
22:50:24 | Info | execute: var eth 0
22:50:24 | Info | execute: if "eth -t" "var eth 1" else "if \"eth -wt\" \"var eth 2\""
22:50:24 | Info | execute: eth -t
22:50:24 | Error | w5500.mac: w5500_reset(302): reset timeout
22:50:24 | Error | w5500.mac: emac_w5500_init(793): reset w5500 failed
22:50:24 | Error | esp_eth: esp_eth_driver_install(228): init mac failed
22:50:24 | Error | eth: initialise_ethernet(250): install driver
22:50:24 |   | Ethernet on USR-ES1 not available
22:50:24 | Warning | execute: command failed: eth -t = 1
22:50:24 | Info | execute: if "eth -wt" "var eth 2"
22:50:24 | Info | execute: eth -wt
22:50:25 | Error | w5500.mac: w5500_reset(302): reset timeout
22:50:25 | Error | w5500.mac: emac_w5500_init(793): reset w5500 failed
22:50:25 | Error | esp_eth: esp_eth_driver_install(228): init mac failed
22:50:25 | Error | eth: initialise_ethernet(250): install driver
22:50:25 |   | Ethernet on W5500 module not available
22:50:25 | Warning | execute: command failed: eth -wt = 1
22:50:25 | Info | execute: on -o server 2 "after -o -m 500 0 restart"
22:50:25 |   | server trigger installed
22:50:25 | Info | execute: io -a
22:50:25 | Info | execute: function chkethcfg "if \"eth -c\" \"var eth 1\""
22:50:25 |   | function installed
22:50:25 | Info | execute: if "!var isnew" "if \"!var eth\" chkethcfg"
22:50:25 | Info | execute: var isnew
22:50:25 |   | variable isnew = 0
22:50:25 | Info | execute: if "!var eth" chkethcfg
22:50:25 | Info | execute: var eth
22:50:25 |   | variable eth = 0
22:50:25 | Info | execute: chkethcfg
22:50:25 | Info | execute: if "eth -c" "var eth 1"
22:50:25 | Info | execute: eth -c
22:50:25 | Warning | execute: command failed: eth -c = 1
22:50:25 | Info | execute: function enet eth "led 0 50" "led 1 50" "led 2 50"
22:50:25 |   | function installed
22:50:25 | Info | execute: if "isnvs eth.on" "if \"var eth\" enet"
22:50:25 | Info | execute: isnvs eth.on
22:50:25 | Warning | execute: command failed: isnvs eth.on = 1
22:50:25 | Info | execute: function ebusnvs ebus "led 0 50"
22:50:25 |   | function installed
22:50:25 | Info | execute: if "isnvs ebus.host" ebusnvs exit
22:50:25 | Info | execute: isnvs ebus.host
22:50:25 | Info | execute: ebusnvs
22:50:25 | Info | execute: ebus
22:50:25 | Info | init_ebus: switching to enhanced eBUS mode on TCP port (with bitrate deviation 0 and enhanced arbitration delay 600 us)
22:50:25 | Info | setup_uart: eBUS UART 1 on TX=10(inv) RX=7(inv) with 2400 Bd
22:50:25 | Info | uart: ALREADY NULL
22:50:25 | Info | host_task_tcp: listening
22:50:25 | Info | init_ebus: timer started
22:50:25 | Info | execute: led 0 50
22:50:25 | Info | execute: exit
22:50:25 | Info | execute: command exit
22:50:25 | Info | execute: command exit
22:50:25 | Info | replExecuteFromFile: successfully executed 41/41 commands from '/data/main.eas'
22:50:25 |   | Welcome to eBUS Adapter Shield Interface! Type 'help' to get the list of commands.
22:50:25 |   | Your terminal application does not support escape sequences.
22:50:25 | Info | main_task: Returned from app_main()
22:50:27 | Info | statusLedTimerFn: duty set to 10
22:50:27 | Info | statusLedTimerFn: duty set to 50

ebusd.log
` 
root@ebusd:~# tail -f /var/log/ebusd.log
2023-10-20 20:52:51.555 [main info] successfully read file broadcast.csv
2023-10-20 20:52:51.555 [main info] reading file memory.csv
2023-10-20 20:52:51.555 [main info] successfully read file memory.csv
2023-10-20 20:52:51.555 [main info] read config files, got 11 messages
2023-10-20 20:52:51.587 [bus notice] device status: resetting
2023-10-20 20:52:51.587 [main info] registering data handlers
2023-10-20 20:52:51.587 [main info] registered data handlers
2023-10-20 20:52:51.587 [bus notice] bus started with own address 31/36
2023-10-20 20:52:51.849 [bus notice] device status: reset, supports info
2023-10-20 20:52:51.956 [bus notice] device status: extra info: firmware 1.1[3a0f].1[3a0f], jumpers 0x0f
`

ebusctl:

`
root@ebusd:~# ebusctl -p 9000
localhost: info
version: ebusd 23.2.23.2
device: 192.168.178.119:9999, enhanced, firmware 1.1[3a0f].1[3a0f]
signal: no signal
reconnects: 0
masters: 1
messages: 11
conditional: 0
poll: 0
update: 4
address 31: master #8, ebusd
address 36: slave #8, ebusd

localhost: scan
empty

localhost: find
broadcast datetime = no data stored
broadcast error = no data stored
broadcast id = no data stored
broadcast id = no data stored
broadcast signoflife = no data stored
memory eeprom = no data stored
memory ram = no data stored

localhost:
`

ebusd Optionen

`
EBUSD_OPTS="  --device=ens:192.168.178.119:9999 -p 9000 --latency=10000 --receivetimeout=25000 --loglevel=info -l /var/log/ebusd.log --lograwdatafile=/var/log/ebusrawdata.log --httpport=9001 --htmlpath=/var/www/ebus/html/ --configpath=/etc/ebusd/config/ --scanconfig"
`

Vielen Dank für das Projekt und die Mühe

**Comment by john30** [comment]
check if the eBUS connector really has voltage on it (should be something between 10 and 20V).
