### ISSUE TITLE
scanconfig issue "Kromschroeder"

### ISSUE THREAD

**Issue by ThiloDr** [john30/ebusd-esp32#33]
Hi,
I'm using the standard options:
EBUSD_OPTS="--scanconfig -d ens:/dev/ttyACM0"

pi@raspberrypi:~ $ ebusctl i
version: ebusd 23.2.23.2
update check: invalid request
device: /dev/ttyACM0, enhanced high speed, firmware 1.1[3612].1[3612]
signal: acquired
symbol rate: 50
max symbol rate: 78
min arbitration micros: 16
max arbitration micros: 24
min symbol latency: 4
max symbol latency: 8
scan: finished
reconnects: 0
masters: 6
messages: 16
conditional: 0
poll: 0
update: 4
address 03: master #11
address 08: slave #11, scanned "MF=Kromschroeder;ID=  3B ;SW=" error: ERR: argument value out of valid range
address 10: master #2
address 15: slave #2, scanned "MF=Kromschroeder;ID=  ;SW=0204;HW=-"
address 30: master #3
address 31: master #8, ebusd
address 35: slave #3, scanned "MF=Kromschroeder;ID=  ;SW=0204;HW=-"
address 36: slave #8, ebusd
address 71: master #9
address 76: slave #9, scanned "MF=Kromschroeder;ID=  ;SW=0227;HW=-"
address f1: master #10
address f6: slave #10, scanned "MF=Kromschroeder;ID=  ;SW=0204;HW=-"

To me it seems, that data is received but it can't be interpreted. Sorry if it's a stupid question, but did I miss something in the configuration?
Thanks
Thilo

**Comment by john30** [comment]
not a firmware issue, but anyway: the scan result of Kromschroeder devices is known to not be spec compliant. but this does not lead to other errors or wrong behaviour anyway
