### ISSUE TITLE
WIFI Access Point “EBUS” nach Konfigurationsänderung nicht mehr verfügbar

### ISSUE THREAD

**Issue by Norb1204** [john30/ebusd-esp32#35]
Hallo,
nach der Konfigurationsänderung im Adapter (Host-Verbindung auf USB eingestellt) und Reboot via Webbrowser, wird der WIFI Access Point “EBUS” nicht mehr angezeigt. Ist das normal?
Nach dem erneuten Flashen der Firmware ist der AP wieder sichtbar.

eBUS Adapter 5, Version 2023-10-15

**Comment by john30** [comment]
this is the intended behaviour. if you want the AP on permanently, just configure it in the UI
