### ISSUE TITLE
After Upgrade to 2023-12-17 "API retrieval failed for /status: timeout"

### ISSUE THREAD

**Issue by Fortune95** [john30/ebusd-esp32#38]
It looks like the ethernet module USR-ES1 is no longer recognized correctly. The webinterface is still accessible via ethernet but the ebus device string is only offered for USB. 
![1](https://github.com/john30/ebusd-esp32/assets/68267780/a909b6f5-c98b-47c2-a17a-0b6f642976b1)
With old version 2023-10-15 it works again.

**Comment by john30** [comment]
good spot, thanks!

**Comment by john30** [comment]
new version 20231223 fixes this
