### ISSUE TITLE
Changing heater parameters

### ISSUE THREAD

**Issue by mihaimdinca** [john30/ebusd-esp32#39]
I managed to connect the ebusd and my Ariston Genus One heater (Ariston Genus One + Cube S Net + RPi4B + HAOS + eBUSd addon + ariston.csv provided by komw) and it creates entities that show parameters of the heater as sensors provided by the MQTT integration. My issue is how do I change parameters, like setting temperatures for example.

**Comment by john30** [comment]
not related to the firmware (therefore closing it), but anyway, see here: https://github.com/john30/ebusd/wiki/3.3.-MQTT-client#mqtt-topics
when using json format, for writing anyway the ebusctl input format needs to be used (see [ebusd#588](https://github.com/john30/ebusd/issues/588))
