### ISSUE TITLE
After setup

### ISSUE THREAD

**Issue by ariejoosse** [john30/ebusd-esp32#41]
Hi, I have updated the build on the ESP device and configured the Wifi.
The status says: eBUS signal acquired. ebusd connected: no

How do I go from here? The 'first steps to start using the adapter' does not help me any further. I installed ebusd on a separate device. Now what?

Please help.

Regards,
Arie

**Comment by john30** [comment]
look at the [overview graphic](https://adapter.ebusd.eu/v5/index.en.html#connections).
you need to pass the ip of the adapter as parameter to ebusd, this is also explained (rather explicit I'd say) [in the docs](https://adapter.ebusd.eu/v5/steps.en.html#ebusdcfg).
the adapter also reveals the [device string on the top of the web UI](https://adapter.ebusd.eu/v5/easi.en.html#web)
