### ISSUE TITLE
ebusd in hassio

### ISSUE THREAD

**Issue by mintgroen** [john30/ebusd-esp32#42]
Running through the configuration, wifi connection was a breeze.
Connected the adapter to the ebus lines of my heatpump installation, status reads:

ebusd connected: no
eBUS signal: acquired

I found out that you also need to install a deamon on a rpi or something to handle the communication between the adapter and for say, MQTT. Correct?

Now the problem, since I moved to a new home (which ran mostly node red for all automatitions) I also moved to Home assistant, but hassio is not suited to install any non HA applications like the deamon, right? Do I need to revert back to Raspverry PI OS and put HA in a Docker, or is there another solution (I do I mistunderstand the installation guidelines)

**Comment by john30** [comment]
yes, ebusd can do that as documented: https://adapter.ebusd.eu/v5/index.en.html#connections 
for HA with supervisor you could use the addon, see here: https://github.com/john30/ebusd/wiki/MQTT-integration#home-assistant
