### ISSUE TITLE
Ebus to MQTT

### ISSUE THREAD

**Issue by vlak6613** [john30/ebusd-esp32#43]
Hello people, I am having problems connecting the ebus adapter to Hassio.
I have been running the home assistant server on a raspberry pi and the web interface with the ebus adapter and the correct firmware is also up and running.
Only I have no idea how to get MQTT working now. I have been looking up the necessary information for a few days now, but I have no idea how to approach this now. Do I have to do something in the web interface of the ebus adapter or do I have to get started in hassio. anyone have any ideas?

**Comment by vlak6613** [comment]
I managed it with the ebusd app in hassio. 

Only now I get this error. Is that because I haven't connected the boiler yet?
2023-12-30 14:33:35.436 [bus error] unable to open 192.168.178.67:9999: ERR: generic I/O error
2023-12-30 14:33:35.436 [bus notice] device invalid

Just to be clear, I have not yet connected my central heating boiler to the eBUS

**Comment by john30** [comment]
is 192.168.178.67 the ip address of the adapter?
for MQTT you need to configure ebusd accordingly.

**Comment by vlak6613** [comment]
Yes. Thats the correct ip. Op 31 dec 2023 om 10:29 heeft John ***@***.***> het volgende geschreven:﻿
is 192.168.178.67 the ip address of the adapter?
for MQTT you need to configure ebusd accordingly.

**Comment by john30** [comment]
as stated before: for MQTT you need to configure ebusd accordingly, see here: https://github.com/john30/ebusd/wiki/2.-Run#mqtt-options
not an adapter issue anyway, so closing
