### ISSUE TITLE
Connecting to Wi-Fi network fails

### ISSUE THREAD

**Issue by brz** [john30/ebusd-esp32#5]
I received my v5 in the mail yesterday but I am unable to connect it to my Wi-Fi network.
I installed firmware version 2023-06-18 and after select the Wi-Fi network and entering the password, I get the following screen:
![afbeelding](https://github.com/john30/ebusd-esp32/assets/1662000/923fc395-e471-4f4e-bb29-1f71947cb198)

Afterwards the connection times out:
![afbeelding](https://github.com/john30/ebusd-esp32/assets/1662000/433f1a84-56a8-4f95-9265-1bc428ee6dc1)

I am 100% certain that the password is correct. My Wi-Fi network supports 2.4GHz and 5Ghz but the 5Ghz network is not stable. It support Wi-Fi N (not ac or ax). I run OpenWRT on my router.

Since this didn't work I tried connecting to the EBUS AP from my smartphone,
I can connect to the AP and was able to configure it successfully this way.

**Comment by farfade** [comment]
Hello @john30,

I've got the same problem here.

Can you be more explicit on what security protocols are supported by the firmware for Wifi connexion ?
WPA2 ? WPA ? WEP ?

Note that WEP and WPA are weak and do not provide security.

Thanks for reading.

**Comment by john30** [comment]
it supports what esp-idf does at the development branch of the build date, so there is no limitation on using 2.4 or 5 GHz e.g.

if you need a fix IP, you can connect to the easi AP "EBUS" and adjust the IP settings for station mode accordingly (IMRPOV does not support setting a fix IP).

**Comment by john30** [comment]
fix ip for wifi was added some releases ago, failed connect logging should be there already. so please check again and if it still fails, then post the output of the log command via serial repl

**Comment by john30** [comment]
closed for inactivity
