### ISSUE TITLE
easi> Configuration page, MQTT Broker URI can't handle more than 32 character instead of the reported 64

### ISSUE THREAD

**Issue by etmmafl** [john30/ebusd-esp32#58]
The problem is in easi> Configuration page, **MQTT Broker URI** 
The text field can't handle more than 32 character instead of the reported 64

I had to truncate my login and password details to get this working.

![afbeelding](https://github.com/john30/ebusd-esp32/assets/19225255/94651af4-6591-4b27-b861-b0afaddcea9e)

Build: [20240420]
WiFi station/client: XXXXXXX 192.168.68.145, 90% (-55dBm)
WiFi access point: inactive
Chip ID: 348518f7c6d8, [ESP32-C3, rev 4]
Hostname: ebus-xxxxxxx
ebusd connected: no
eBUS signal: no signal
MQTT connected: yes

**Comment by john30** [comment]
good spot, thanks. just a little too tight validation here :) will be fixed in next release.
you can circumvent for now by using the repl, i.e. `nvs_set mqtt.uri str -v "..."`

**Comment by Curtain4win** [comment]
> good spot, thanks. just a little too tight validation here :) will be fixed in next release. you can circumvent for now by using the repl, i.e. `nvs_set mqtt.uri str -v "..."`

unfortunately then it does not allow to reboot or save via gui of easi>

**Comment by john30** [comment]
it is saved when using that command and a reboot is as simple as entering "restart" to the repl.
anyway, fixed with the [new version 20240505](https://adapter.ebusd.eu/v5/ChangeLog#20240505) just published
