### ISSUE TITLE
Firmware update shows "ESP_ERR_INVALID_ARG"

### ISSUE THREAD

**Issue by JavanXD** [john30/ebusd-esp32#60]
Error message:
`Status: already up-to-date, error: ESP_ERR_INVALID_ARG`

Screenshot:
![Screen Shot 2024-05-03 at 12 17 35 PM](https://github.com/john30/ebusd-esp32/assets/4342160/a480e061-6602-428a-9a2f-dd6ad4184a89)

Happens after clicking on "Test".

**Comment by john30** [comment]
you need to read... "already up-to-date" - what could that possibly mean?

**Comment by JavanXD** [comment]
If everything is all right, why then printing out "error: ...".

**Comment by john30** [comment]
one could argue that it is an error to update to the version already present. never mind, will be gone in next release
