### ISSUE TITLE
Wrong log level for "vfs: esp_vfs_register_fd_range is successful for range <52; 64) and VFS ID 3"

### ISSUE THREAD

**Issue by JavanXD** [john30/ebusd-esp32#62]
Every time I boot I the ebusd Adapter I get the following Warning:

`WARNING | vfs: esp_vfs_register_fd_range is successful for range <52; 64) and VFS ID 3`

![Screen Shot 2024-05-03 at 12 37 58 PM](https://github.com/john30/ebusd-esp32/assets/4342160/4a1cabfb-b303-43e6-98e9-b66323e5b257)

As the command is executed successful, shouldn't this be a "Informational" log entry and not a Warning? I see this Warning every time I reboot.

**Comment by john30** [comment]
applied another path to ESP-IDF in the [new version 20240505](https://adapter.ebusd.eu/v5/ChangeLog#20240505)
