### ISSUE TITLE
[Parameter request] Disable the default AP mode at startup

### ISSUE THREAD

**Issue by farfade** [john30/ebusd-esp32#7]
Hello @john30,

First, thank you for this amazing device 👍 

When I start the V5 adapter, the wifi is both in AP mode and in client mode. 

At the startup time, I can access the web client through its client address.
About two minutes after, the web client becomes unresponsive.
I have to wait for approximately 10 minutes in order to have things become responsive again. At this time, the startup AP mode is reported as inactive.

The only thing I can imagine is some side effect of the default AP automatic disablement on the wifi client mode.

I'd really like to have a parameter to disable the AP mode at startup : keep it simply stupid :)
If I'm lost, I can come back to USB wire to take back control.
Moreover, it is a security hole at every startup (including after a power outage).

I've tried "ap --store --off", but it does not seem to work.

Thanks for reading !

**Comment by john30** [comment]
when station is configured, easi will start both network mode, station and ap. ap is only run for up to 2 minutes to get a chance to reconfigure the adapter, but this will be removed in the next version

**Comment by farfade** [comment]
Many thanks !
