### ISSUE TITLE
Dumping Configuration feature missing?

### ISSUE THREAD

**Issue by wrongisthenewright** [john30/ebusd-esp32#72]
No issue here, I just updated a V5 adapter to last build, all OK. I was wondering if there's an option to dump the entire configuration.
I'm thinking of buying another adapter as a failsafe in case the one I'm using just dies.
I gave a cursory look at the web interface and to the REPL CLI but I wasn't able to solve.
Not a great problem but I think it would be useful.

Many thanks

**Comment by john30** [comment]
http://adapterip/api/v1/config just as the UI does
