### ISSUE TITLE
After a power outage the adapter does not work

### ISSUE THREAD

**Issue by edudele** [john30/ebusd-esp32#77]
Good morning, After a power outage the adapter does not work

Version:

Chip ID: 543204291658, [ESP32-C6, rev 1](http://192.168.1.202/#/status?verbose)
Hostname: ebusd-c6
Up time: 886
Free heap: 190288 / 366744
ebusd connected: yes (inactive)
eBUS signal: acquired
MQTT connected: yes

Build: [20241027](https://adapter.ebusd.eu/v5-c6/ChangeLog#20241027)
[ebusd device string](https://github.com/john30/ebusd/wiki/2.-Run#device-options): "ens:/dev/ttyACM0" (number may vary)
WiFi station/client: VILLAMANIN, 192.168.1.202, 96% (-52dBm)
WiFi access point: inactive

`

11:25:23 |   | [5n
-- | -- | --
11:25:23 | Info | replExecuteFromFile: executing commands from '/data/boot.eas'
11:25:23 | Info | execute: strip -m 1 -b 255
11:25:23 | Info | gpio: GPIO[23]\| InputEn: 0\| OutputEn: 1\| OpenDrain: 0\| Pullup: 1\| Pulldown: 0\| Intr:0
11:25:23 | Info | execute: function ledb "@strip -b"
11:25:23 |   | function 'ledb' installed
11:25:23 | Info | execute: function ledg "@strip -g"
11:25:23 |   | function 'ledg' installed
11:25:23 | Info | execute: led -p 16 -i 0 255
11:25:23 |   | 0 duty set to 254
11:25:23 | Info | execute: function ledboot "@led 0"
11:25:23 |   | function 'ledboot' installed
11:25:23 | Info | execute: function leds "@strip -b" "@led 0"
11:25:23 |   | function 'leds' installed
11:25:23 | Info | execute: io -iue 9
11:25:23 |   | IO 9 direction set to 01
11:25:23 |   | IO 9 pull set to 00
11:25:23 |   | IO 9 = 1
11:25:23 | Info | execute: io -iu 6
11:25:23 |   | IO 6 direction set to 01
11:25:23 |   | IO 6 pull set to 00
11:25:23 |   | IO 6 = 1
11:25:23 | Info | execute: nvs_namespace easi
11:25:23 | Info | cmd_nvs: Namespace set to 'easi'
11:25:23 | Info | replExecuteFromFile: successfully executed 9/9 commands from '/data/boot.eas'
11:25:23 | Info | replExecuteFromFile: executing commands from '/data/main.eas'
11:25:23 | Info | execute: var skipstart 0
11:25:23 | Info | execute: leds 255 0 700
11:25:23 | Info | execute: strip -b 255 0 700
11:25:23 | Info | execute: led 0 255 0 700
11:25:23 |   | 0 duty set to 254
11:25:23 | Info | execute: sleep 1000
11:25:23 | Info | main_task: Returned from app_main()
11:25:24 | Info | execute: if "isio -l 9" "var skipstart 1"
11:25:24 | Info | execute: isio -l 9
11:25:24 |   | IO 9 level 1 is unmet
11:25:24 | Info | execute: leds 255 0 700
11:25:24 | Info | execute: strip -b 255 0 700
11:25:24 | Info | execute: led 0 255 0 700
11:25:24 |   | 0 duty set to 254
11:25:24 | Info | execute: sleep 1000
11:25:25 | Info | execute: if "isio -l 9" "var skipstart 1"
11:25:25 | Info | execute: isio -l 9
11:25:25 |   | IO 9 level 1 is unmet
11:25:25 | Info | execute: leds 255 0 700
11:25:25 | Info | execute: strip -b 255 0 700
11:25:25 | Info | execute: led 0 255 0 700
11:25:25 |   | 0 duty set to 254
11:25:25 | Info | execute: sleep 1000
11:25:26 | Info | execute: if "isio -l 9" "var skipstart 1"
11:25:26 | Info | execute: isio -l 9
11:25:26 |   | IO 9 level 1 is unmet
11:25:26 | Info | execute: var rpi 0
11:25:26 | Info | execute: if "isio -l 6" "var rpi 1"
11:25:26 | Info | execute: isio -l 6
11:25:26 |   | IO 6 level 1 is unmet
11:25:26 | Info | execute: var isnew 1
11:25:26 | Info | execute: if "§isnvs ebus.host" "var isnew 0"
11:25:26 | Info | execute: isnvs ebus.host
11:25:26 | Info | execute: var isnew 0
11:25:26 |   | variable isnew = 0
11:25:26 | Info | execute: if "§isnvs sta.on" "var isnew 0"
11:25:26 | Info | execute: isnvs sta.on
11:25:26 | Info | execute: var isnew 0
11:25:26 | Info | execute: if "§isnvs eth.on" "var isnew 0"
11:25:26 | Info | execute: isnvs eth.on
11:25:26 | Warning | execute: command failed: isnvs eth.on = 1
11:25:26 | Info | execute: on -lo iol 9 "leds 255" "sleep 500" restart
11:25:26 |   | io trigger installed
11:25:26 | Info | execute: on iol 9 "ledboot 50 0"
11:25:26 |   | io trigger installed
11:25:26 | Info | execute: function start "ledg 50 0 3000" server mqtt
11:25:26 |   | function 'start' installed
11:25:26 | Info | execute: on -o wifi 1 start
11:25:26 |   | network trigger installed
11:25:26 | Info | execute: on -o eth 1 start
11:25:26 |   | network trigger installed
11:25:26 | Info | execute: on wifi 0 "ledb 0"
11:25:26 |   | network trigger installed
11:25:26 | Info | execute: on eth 0 "ledb 0"
11:25:26 |   | network trigger installed
11:25:26 | Info | execute: on -o server 2 "after -o -m 500 0 restart"
11:25:26 |   | server trigger installed
11:25:26 | Info | execute: if "var skipstart" "ledb 255 0 5000" "ledboot 50" "ap EBUS" start exit
11:25:26 | Info | execute: var skipstart
11:25:26 |   | variable skipstart = 0
11:25:26 | Info | execute: if "isnvs sta.on" "ledb 10 255 5000" "sleep 100" sta
11:25:26 | Info | execute: isnvs sta.on
11:25:26 | Info | execute: ledb 10 255 5000
11:25:26 | Info | execute: strip -b 10 255 5000
11:25:26 | Info | execute: sleep 100
11:25:27 | Info | execute: sta
11:25:27 | Warning | event: handler already registered, overwriting
11:25:27 |   | using individual IP: 192.168.1.202 / 255.255.255.0, gateway 192.168.1.1
11:25:27 |   | sta connecting to 'VILLAMANIN'
11:25:29 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:31 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:32 |   | error: unable to connect to 'VILLAMANIN'
11:25:32 | Warning | execute: command failed: sta = 1
11:25:32 | Info | execute: if "var isnew" "ap EBUS" "sta -w" else "if \"isnvs ap.on\" ap"
11:25:32 | Info | execute: var isnew
11:25:32 |   | variable isnew = 0
11:25:32 | Info | execute: if "isnvs ap.on" ap
11:25:32 | Info | execute: isnvs ap.on
11:25:32 | Info | execute: var eth 0
11:25:32 | Info | execute: if "eth -t" "var eth 1" else "if \"eth -wt\" \"var eth 2\""
11:25:32 | Info | execute: eth -t
11:25:33 | Error | w5500.mac: W5500 version mismatched, expected 0x04, got 0x00
11:25:33 |   | Ethernet on USR-ES1 not available
11:25:33 | Warning | execute: command failed: eth -t = 1
11:25:33 | Info | execute: if "eth -wt" "var eth 2"
11:25:33 | Info | execute: eth -wt
11:25:34 |   | Ethernet on W5500 module not available
11:25:34 | Warning | execute: command failed: eth -wt = 1
11:25:34 | Info | execute: io -a
11:25:34 | Info | execute: function chkethcfg "if \"eth -c\" \"var eth 1\""
11:25:34 |   | function 'chkethcfg' installed
11:25:34 | Info | execute: if "!var isnew" "if \"!var eth\" chkethcfg"
11:25:34 | Info | execute: var isnew
11:25:34 |   | variable isnew = 0
11:25:34 | Info | execute: if "!var eth" chkethcfg
11:25:34 | Info | execute: var eth
11:25:34 |   | variable eth = 0
11:25:34 | Info | execute: chkethcfg
11:25:34 | Info | execute: if "eth -c" "var eth 1"
11:25:34 | Info | execute: eth -c
11:25:34 | Warning | execute: command failed: eth -c = 1
11:25:34 | Info | execute: function enet eth "leds 50"
11:25:34 |   | function 'enet' installed
11:25:34 | Info | execute: if "isnvs eth.on" "if \"var eth\" enet"
11:25:34 | Info | execute: isnvs eth.on
11:25:34 | Warning | execute: command failed: isnvs eth.on = 1
11:25:34 | Info | execute: if "isnvs ebus.host" ebus exit
11:25:34 | Info | execute: isnvs ebus.host
11:25:34 | Info | execute: ebus
11:25:34 | Info | init_ebus: switching to enhanced eBUS mode on JTAG (with bitrate deviation 0 and enhanced arbitration delay 200 us)
11:25:34 | Info | setup_uart: eBUS UART 1 on TX=15(inv) RX=14(inv) with 2400 Bd
11:25:34 | Info | uart: queue free spaces: 16
11:25:34 | Info | execute: exit
11:25:34 | Info | execute: command exit
11:25:34 | Info | execute: command exit
11:25:34 | Info | replExecuteFromFile: successfully executed 35/35 commands from '/data/main.eas'
11:25:34 | Info | loop: host reset
11:25:34 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:36 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:38 | Info | loop: host disconnected
11:25:39 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:40 | Info | loop: host reset
11:25:40 | Info | loop: host disconnected
11:25:40 | Info | loop: host reset
11:25:41 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:44 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:46 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:48 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:51 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:53 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:56 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:25:58 | Info | cmd_wifi: sta disconnect, reason 201, reconnect...
11:26:00 | Info | cmd_wifi: sta disconnect, reason 2, reconnect...
11:26:03 | Info | cmd_wifi: sta disconnect, reason 205, reconnect...
11:26:05 | Info | cmd_wifi: sta connect, set fix ip
11:26:05 | Info | repl_event_task: sta event: 1
11:26:05 | Info | execute: start
11:26:05 | Info | execute: ledg 50 0 3000
11:26:05 | Info | execute: strip -g 50 0 3000
11:26:05 | Info | execute: server
11:26:05 | Info | initialise_mdns: mdns configured
11:26:05 | Info | esp-rest: Starting HTTP Server
11:26:05 |   | server started
11:26:05 | Info | execute: mqtt
11:26:05 |   | MQTT client started
11:26:06 | Info | temperature_sensor: Range [-10°C ~ 80°C], error < 1°C
11:26:13 | Error | handleHostRx: invalid plain 5e
11:26:13 | Error | handleHostRx: invalid plain 50
11:26:13 | Error | handleHostRx: invalid plain 76
11:26:13 | Error | handleHostRx: invalid plain 5e
11:26:13 | Error | handleHostRx: invalid plain 50
11:26:13 | Error | handleHostRx: invalid plain 09
11:26:13 | Error | handleHostRx: invalid plain 5e
11:26:13 | Error | handleHostRx: invalid plain 40
11:26:13 | Error | handleHostRx: invalid plain 5e
11:26:13 | Error | handleHostRx: invalid plain 5e
11:26:13 | Error | handleHostRx: invalid plain 41
11:26:13 | Error | handleHostRx: invalid plain 5e
11:26:13 | Error | handleHostRx: invalid plain 47
11:26:13 | Error | handleHostRx: invalid plain 5e
11:26:13 | Info | mqtt: connected
11:26:13 | Info | mqtt: subscribed topic 62603 ebusd/adaptador/#
11:26:23 | Error | handleHostRx: invalid plain 40
11:26:23 | Error | handleHostRx: invalid plain 0a
11:26:23 | Error | handleHostRx: invalid plain 5e
11:26:23 | Error | handleHostRx: invalid plain 40
11:26:23 | Error | handleHostRx: miss b2 c6
11:26:23 | Error | handleHostRx: unexp b2 b1
11:26:30 | Info | sntpTimeCb: got NTP time: 2024-10-28 10:26:31
11:37:00 | Error | handleHostRx: unexp b2 b1

And the demon goes into a loop:

> 2024-10-28 11:43:16.842 [update notice] received unknown MS cmd: 1076b51009000000ffffff050000 / 0101
> 2024-10-28 11:43:19.350 [update notice] received unknown MS cmd: 7108b5110107 / 0a00b60081003600000000
> 2024-10-28 11:43:22.178 [main notice] starting initial broadcast scan
> 2024-10-28 11:43:22.289 [bus error] send to fe: ERR: read timeout, retry
> 2024-10-28 11:43:22.902 [bus error] send to fe: ERR: read timeout, retry
> 2024-10-28 11:43:22.924 [bus error] send to fe: ERR: wrong symbol received
> 2024-10-28 11:43:22.924 [main error] initial scan failed: ERR: wrong symbol received
> 2024-10-28 11:43:23.608 [update notice] received unknown MS cmd: 7108b5110107 / 0a00b60081003600000000
> 2024-10-28 11:43:23.822 [update notice] received unknown MS cmd: 0376b512061300124a0300 / 0200ff
> 2024-10-28 11:43:24.306 [update notice] received unknown MS cmd: f108b5110101 / 093b3c0080ffff0000ff
> 2024-10-28 11:43:24.483 [update notice] received unknown MS cmd: f108b5110100 / 09df0112000808000000
> 2024-10-28 11:43:25.712 [update notice] received unknown MS cmd: 1008b5110101 / 093b3c0080ffff0000ff
> 2024-10-28 11:43:25.981 [update notice] received unknown MS cmd: 1076b5110101 / 09ffff0080ff410000ff
> 2024-10-28 11:43:26.248 [update notice] received unknown MS cmd: 1076b512030f0101 / 070902000080ff03
> 2024-10-28 11:43:26.387 [update notice] received unknown MS cmd: 7108b5110107 / 0a00b60081003600000000
> 2024-10-28 11:43:26.564 [update notice] received unknown MS cmd: 1008b51009000045ffffff060000 / 0101
> 2024-10-28 11:43:26.829 [update notice] received unknown MS cmd: 1076b51009000000ffffff050000 / 0101
> 2024-10-28 11:43:29.688 [update notice] received unknown MS cmd: 7108b5110107 / 0a00b60081003600000000
> 2024-10-28 11:43:30.313 [update notice] received unknown MS cmd: f115b52406020000004800 / 06010048000100
> 2024-10-28 11:43:30.499 [update notice] received unknown MS cmd: f115b52406020002001e00 / 0601021e000100
> 2024-10-28 11:43:30.624 [update notice] received unknown MS cmd: 0376b512061300124a0300 / 0200ff
> 2024-10-28 11:43:30.730 [update notice] received unknown MS cmd: f115b52406020003002200 / 08030322000000b041
> 2024-10-28 11:43:30.924 [update notice] received unknown MS cmd: f115b52406020003001400 / 08010314000000b041
> 2024-10-28 11:43:31.110 [update notice] received unknown MS cmd: f115b52406020003000600 / 06030306000200
> 2024-10-28 11:43:31.296 [update notice] received unknown MS cmd: f115b52406020003001b00 / 0601031b000000
> 2024-10-28 11:43:31.481 [update notice] received unknown MS cmd: f115b52406020001000f00 / 0601010f000000
> 2024-10-28 11:43:32.924 [main notice] starting initial broadcast scan
> 2024-10-28 11:43:33.015 [bus error] send to fe: ERR: read timeout, retry
> 2024-10-28 11:43:33.628 [bus error] send to fe: ERR: read timeout, retry

**Comment by edudele** [comment]
It would be possible to generate a topic within the adapter to send to force a restart of the adapter itself.
![image](https://github.com/user-attachments/assets/7bcba758-85a5-4d8f-b497-1bc6e08a4675)

**Comment by john30** [comment]
how is ebusd started, i.e. with which arguments?

**Comment by edudele** [comment]
After the power outage, possibly the daemon was not even started, it is with docker on a minipc, but the adapter

**Comment by john30** [comment]
that does not answer my question, but anyway:
maybe you did not configure the container to restart after reboot

**Comment by edudele** [comment]
> that does not answer my question, but anyway: maybe you did not configure the container to restart after reboot

When we get to opening an issues it's because I have a real problem and I want to help make this work better. Here is what you asked for, I have been studying ebusd and its files for 2-3 years, to send us with that answer.

As I said before, it is not the container.
Here is my docker compose:

```
version: '3' 
services:
    ebusd:
        container_name: ebusdv5
        restart: unless-stopped
        #image: john30/ebusd:devel
        image: john30/ebusd:latest
        #image: john30/ebusd:v23.2
        privileged: true
        environment:
          - EBUSD_SCANCONFIG=full
          - EBUSD_CONFIGPATH=/ebusd/ebusd-configuration/ebusd-2.1.x/en
          #- EBUSD_LOGAREAS=all
          #- EBUSD_LOGLEVEL=info
          - EBUSD_ACCESSLEVEL=*
          - EBUSD_DEVICE=ens:/dev/ttyACM0
          #- EBUSD_DEVICE=ens:192.168.1.202:9999
          - EBUSD_MQTTHOST=mosquitto
          - EBUSD_MQTTPORT=1883
          - EBUSD_MQTTUSER=xxxxx
          - EBUSD_MQTTPASS=xxxx
          - EBUSD_MQTTJSON=
          - EBUSD_LATENCY=10
          - EBUSD_MQTTINT=/ebusd/ebusd-configuration/mqtt-hassio.cfg
          #- EBUSD_MQTTTOPIC=
        volumes:
          - /docker/ebusd/:/ebusd
          - /etc/localtime:/etc/localtime:ro
        devices:
          - /dev/ttyACM0:/dev/ttyACM0
```

**Comment by john30** [comment]
> I have been studying ebusd and its files for 2-3 years, to send us with that answer.

no idea what you're trying to tell me with this.

> As I said before, it is not the container.

which contradicts with what you wrote before:
> ...possibly the daemon was not even started yet...

and still you didn't provide the logging I asked for, so how would I know whats going on??
and did you check after the reboot that the container was actually running?

**Comment by edudele** [comment]
luck
