### ISSUE TITLE
Version 2024-10-27 causing bus errors, Version 2024-10-08 works

### ISSUE THREAD

**Issue by dwing33** [john30/ebusd-esp32#79]
It reads from some slaves, but not all. E.g. Vaillant HMU (address 0x08) doesn't work.
I've reverted back to previous version.

**Comment by john30** [comment]
hard to tell without any logging

**Comment by dwing33** [comment]
New try this evening and now it seems there's no issue. Firmware reboots adapter anyway, I've restarted the container with ebusd and no issue anymore.
