### ISSUE TITLE
Helioset saunier Duval problem with the signal ebusd v6

### ISSUE THREAD

**Issue by didjerislade** [john30/ebusd-esp32#81]
Hi,

I would like to monitor some parameters of my Helioset but when I connect my ebus adapter v6 to the ebus port I don't get any signal. ebus connected: yes but inactive 

Has anyone had any experience with this kind of devices?

Thanks in advance.

**Comment by john30** [comment]
probably insufficient support for this heating, so an [ebusd-configuration](https://github.com/john30/ebusd-configuration) issue instead.

**Comment by adrianoapmartins** [comment]
Hey @didjerislade, did you have any luck with this?

**Comment by didjerislade** [comment]
it's seems that it can't work anyway..

**Comment by john30** [comment]
if the bus does not have a signal at all, you can try [--generatesyn](https://github.com/john30/ebusd/wiki/2.-Run#ebus-options)
