### ISSUE TITLE
Wemos C3 mini + 2.x adapter.

### ISSUE THREAD

**Issue by Mozzarella7** [john30/ebusd-esp32#85]
I plan to replace wemos d1 mini on my old v2.x adapter with wemos C3. Is there someone who use such setup and could share ebus protocol and pin setup for standard, wi-fi connection. Thanks in andvance.

**Comment by john30** [comment]
it is shown in the web ui when you flash the wemos with the firmware

**Comment by LeZerb** [comment]
@Mozzarella7 have you had a look at https://github.com/john30/ebusd-esp32/issues/49 and https://github.com/john30/ebusd/discussions/978 ?

**Comment by Mozzarella7** [comment]
@LeZerb , read that but its does not help. Tried to set it up similar to D1 mini but no ebus connection.
![1](https://github.com/user-attachments/assets/b3f68ba4-9b08-4f80-b2c2-33eb5f451617)
![2](https://github.com/user-attachments/assets/810b1fd6-7d6a-4651-8d06-ead130c5efbe)
