### ISSUE TITLE
RGB LED: How can i deactivate or dimm the RGB LED?

### ISSUE THREAD

**Issue by Dobie007** [john30/ebusd-esp32#87]
The RGB LED is causing familly trouble because it is too bright and looks like a Fire alarm.
Is there any way to change the brightness other than using a soldering iron or a pair of pliers?
I am using the latest C6 version..
:-)

**Comment by john30** [comment]
just turn off the visual ping and tx led in the config/ebus section

**Comment by Dobie007** [comment]
ouch, thanks
